# config.yml
n: 7          # base VNs -> k in final code (cols of H)
m: 5          # base CNs  (rate ≈ 0.5 after lifting) (rows of H)
scaling_factor: 3   # final n_phys = n * scaling_factor
girth_search_depth: 4
seed: 42
lam_node: [0, 0, 1]         # all VNs degree 3
rho_node:   # all CNs degree 6
output_fname : "pegs/peg_7_5_3_0-1.qc"