n : 4  #Number of variable nodes (columns) in protograph
m : 4   #Number of check nodes (rows) in protograph
scaling_factor : 3  #Scaling of the protograph, often refered to as N
girth_search_depth : 1 #Maximum depth of the DFS search algorithm to calculate potential girth
seed : None #Randomness seed, set to None to pick a new one every time.
input_fname : 
output_fname : "test.qc" #Output file useable with aff3ct